In [1]:
# use keras deep learning library and split write a code with encoding one_hot
import numpy as np
from keras.utils import to_categorical
category=["apple","orange","kiwi","orange","banana"]
Total_category=["apple","orange","kiwi","banana","litchi"]
mapping={}
for x in range(len(Total_category)):
  mapping[Total_category[x]]=x
for x in range(len(category)):
  category[x]=mapping[category[x]]
one_hot_encode=to_categorical(category)
print(one_hot_encode)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#CODE WITH DATA SET


# import numpy as np
# import pandas as pd
# data=pd.read_csv('/content/USA_cars_datasets[1].csv')
# print(data.head())
# print(data['brand'].unique())
# print(data['state'].unique())
# data['brand'].value_counts()
# data['state'].value_counts()
# one_hot_encoded_data=pd.get_dummies(data,columns=['state','brand'])
# print(one_hot_encoded_data)